env:
  matrix:
    - LISP=sbcl
    - LISP=allegro

matrix:
  allow_failures:
    - env: LISP=allegro
    
script:
  - cl -e '(ql:quickload :ttt)
           (ql:quickload :uiop)
           (unless (ttt:run-tests)
             (uiop:quit 1))'
