language: lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=allegro
    - LISP=abcl
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    - env: LISP=allegro
    # CIM not available for CMUCL
    - env: LISP=cmucl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
  
before_script:
  - echo "(defsystem :dummy-cl-travis-system)" > ~/lisp/dummy-cl-travis-system.asd

script:
  - cl -e '(ql:quickload :ttt)
           (ql:quickload :uiop)
           (in-package :ttt)
           (load-tests-all)
           (compile-tests)
           (run-tests)'
