language: lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=allegro
    - LISP=allegromodern
    - LISP=abcl
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    # Only plan to support SBCL, but check compatilibity issues on other
    # distributions.
    - env: LISP=allegro
    - env: LISP=allegromodern
    - env: LISP=abcl
    - env: LISP=ccl
    - env: LISP=ccl32
    - env: LISP=clisp
    - env: LISP=clisp32
    - env: LISP=ecl
    # CIM not available for CMUCL
    - env: LISP=cmucl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
  
before_script:
  - echo "(defsystem :dummy-cl-travis-system)" > ~/lisp/dummy-cl-travis-system.asd

script:
  - cd src; cl -e '(ql:quickload :ttt)
                   (ql:quickload :uiop)
                   (ql:quickload :lisp-unit)
                   (in-package :ttt)
                   (load-tests-all)
                   (compile-tests)
                   (run-tests)
                   (load "run-unit-tests")'
