;; PP Suffixes found from grepping Knext source
(defparameter *pp-suffixes* 
  '(PP-ABOUT PP-ABOVE PP-ACROSS PP-AFTER PP-AFTER-TIME PP-AGAINST PP-AMONG
    PP-AROUND PP-AROUND-TIME PP-AS PP-AT PP-AT-TIME PP-BEFORE PP-BEFORE-TIME
    PP-BEHIND PP-BENEATH PP-BESIDE PP-BETWEEN PP-BETWEEN-TIME PP-BY PP-BY-TIME
    PP-DURING PP-FOR PP-FOR-TIME PP-FROM PP-FROM-TIME PP-IN PP-IN-FRONT-OF
    PP-IN-SPITE-OF PP-IN-TIME PP-INTO PP-OF PP-OFF PP-ON PP-ON-TIME PP-ONTO
    PP-OUT-OF PP-OVER PP-OVER-TIME PP-THROUGH PP-THROUGHOUT PP-THROUGHOUT-TIME
    PP-THROUGH-TIME PP-TIME PP-TO PP-TO-TIME PP-TOWARD PP-UNDER PP-UNTIL
    PP-UNTIL-TIME PP-UPON PP-WITH PP-WITHIN PP-WITHOUT))
