;; This set of rules was written to break apart multiple-leaf constituents.
;; It is not being actively maintained. 
(/ (ADVP (PP-AS-PART-OF (IN AS PART OF) (NP _+))) (PP (IN AS) (NP (NP (NN PART)) (PP (IN OF) (NP _+)))))
(/ (ADVP (PP-IN-ADDITION-TO (IN IN ADDITION TO) (S-NOM _+))) (PP (IN IN) (NP (NP (NN ADDITION)) (PP (TO TO) (S-NOM _+)))))
(/ (ADVP (ADVP (RB PARTICULARLY)) (PP-IN-LIGHT-OF (IN IN LIGHT OF) (NP _+))) (PP (ADVP (RB PARTICULARLY)) (IN IN) (NP (NP (NN LIGHT)) (PP (IN OF) (NP _+)))))
(/ (PP-ON-BEHALF-OF (IN ON BEHALF OF) (NP _+)) (PP (IN ON) (NP (NP (NN BEHALF)) (PP (IN OF) (NP _+)))))
(/ (PP-ON-TOP-OF (IN ON TOP OF) (NP _+)) (PP (IN ON) (NP (NP (NN TOP)) (PP (IN OF) (NP _+)))) )
(/ (PP-IN-CHARGE-OF (IN IN CHARGE OF) (NP _+)) (PP (IN IN) (NP (NP (NN CHARGE)) (PP (IN OF) (NP _+)))))
(/ (PP-IN-LIGHT-OF (IN IN LIGHT OF) (NP _+)) (PP (IN IN) (NP (NP (NN LIGHT)) (PP (IN OF) (NP _+) ))))
(/ (PP-AS-PART-OF (IN AS PART OF) (NP _+)_*) (PP (IN AS) (NP (NP (NN PART)) (PP (IN OF) (NP _+)))))
(/ (PP-IN-ADDITION-TO (IN IN ADDITION TO) (NP _+)) (PP (IN IN) (NP (NP (NN ADDITION)) (PP (IN TO) (NP _+)))))
(/ (PP-IN-ADDITION-TO (IN IN ADDITION TO) _+) (PP (IN IN) (NP (NP (NN ADDITION)) (PP (IN TO) _+))))
(/ (PP-IN-FRONT-OF (IN IN FRONT OF) (NP _+)) (PP (IN IN) (NP (NP (NN FRONT)) (PP (IN OF) (NP _+)))))
(/ (ADJP (JJ UNDER INVESTIGATION)) (PP (IN UNDER) (NP (NNP INVESTIGATION))))
(/ (ADJP (JJ IN TROUBLE)) (PP (IN IN) (NP (NNP TROUBLE))))
(/ (ADJP (JJ AT HOME)) (PP (IN AT) (NP (NNP HOME))))
(/ (VP (VBD TIED IN) (NP _+) _*) (VP (VBD TIED) (NP _+) (PRT (RP IN)) _*))
(/ (VP (VB GIVE UP) (NP _+) _*) (VP (VB GIVE) (NP _+) (PRT (RP UP)) _*))
(/ (VP (VB KEEP DOWN) (NP _+)) (VP (VB KEEP) (NP _+) (PRP (RP DOWN))))
(/ (VP (VB LET DOWN) (NP _+) _*) (VP (VB LET) (NP _+) (PRT (RP DOWN)) _*))
(/ (VP (VBG ROLLING UP) (NP _+)) (VP (VBG ROLLING) (NP _+) (PRT (RP UP))))
(/ (VP (VBN MADE UP) (NP _+) _*) (VP (VBN MADE) (NP _+) (PRT (RP UP)) _*))
(/ (VB (VBN SCALED BACK) (NP _+) _*) (VP (VBN SCALED) (NP _+) (PRT (RP BACK)) _*))
(/ (VP (VBN SERVED UP) (NP _+) _*) (VP (VBN SERVED) (NP _+) (PRT (RP UP)) _*))
(/ (VP (VBN TAKEN  UP) (NP _+) _*) (VP (VBN TAKEN) (NP _+) (PRT (RP UP)) _*))
(/ (VP (VBN THINNED OUT) (NP _+)) (VP (VBN THINNED) (NP _+) (PRT (RP OUT))))
(/ (VP (VBN TIED IN) (NP _+) _*) (VP (VBN TIED) (NP _+) (PRT (RP IN)) _*))
(/ (VP (VB BAIL OUT) (NP _+)) (VP (VB BAIL) (NP _+) (PRT (RP OUT))))
(/ (VP (VB CLIP OFF) (NP _+)) (VP (VB CLIP) (NP _+) (PRT (RP OFF))))
(/ (VP (VB SEEK OUT) (NP _+) (PP-CLR (IN FOR) (NP _+))) (VP (VB SEEK) (NP _+) (PRT (RP OUT)) (PP-CLR (IN FOR) (NP _+))))
(/ (VP (VB SLOW DOWN) (NP _+))  (VP (VB SLOW) (NP _+) (PRT (RP DOWN))))
(/ (VP (VB THRASH OUT) (NP _+) _*) (VP (VB THRASH) (NP _+) (PRT (RB OUT)) _*))
(/ (ADVP (RB AT LEAST)) (PP (IN AT) (ADJP (JJS LEAST))))
(/ (ADVP (RB IN FACT)) (PP (IN IN) (NP (NN FACT))))
(/ (ADVP (RB OF COURSE)) (PP (IN OF) (NP (NN COURSE))))
(/ (VP (VBD CAME UP) _*) (VP (VBD CAME) (PRT (RB UP)) _*))
(/ (VP (VBD HAD BEST) _*) (VP (VBD HAD) (PRT (RBS BEST)) _*))
(/ (VP ((! VBD VB VBG VBN VBEN VBP VBZ) _! _!1) _*)   (VP (! _!) (PRT (RP _!1)) _*))
(/ (NP _*3 ((! NNP NNPS) _* (<> (-LRB- -LRB-) _*1 (-RRB- -RRB-)) _*2) _*4)
   (NP _*3 (! _*) (PRN <>) (!  _*2) _*4))
(/ (NP _* ((! NNP NNPS)) _*1) (NP _* _*1))
(/ (NP _*1 ((! NNP NNPS) (!1 ~ (_*)) (+a ~ (_*))) _*2)  (NP _*1 (! !1) (! +a)_*2))
(/ (NP-TIME _*1 ((! NNP NNPS) (!1 ~ (_*)) (+a ~ (_*))) _*2)  (NP-TIME _*1 (! !1) (! +a)_*2))
